package com.hbm.world;

import com.hbm.blocks.ModBlocks;
import com.hbm.blocks.machine.MachineBattery;
import com.hbm.handler.WeightedRandomChestContentFrom1710;
import com.hbm.itempool.ItemPool;
import com.hbm.itempool.ItemPoolsLegacy;
import com.hbm.items.ModItems;
import com.hbm.lib.Library;
import com.hbm.world.phased.AbstractPhasedStructure;
import it.unimi.dsi.fastutil.longs.LongArrayList;
import net.minecraft.block.Block;
import net.minecraft.block.BlockChest;
import net.minecraft.block.BlockStairs;
import net.minecraft.init.Blocks;
import net.minecraft.item.ItemStack;
import net.minecraft.util.EnumFacing;
import net.minecraft.util.math.BlockPos.MutableBlockPos;
import net.minecraft.world.World;
import net.minecraftforge.items.CapabilityItemHandler;
import net.minecraftforge.items.IItemHandlerModifiable;
import org.jetbrains.annotations.NotNull;

import java.util.Random;

@SuppressWarnings({"UnnecessaryUnaryMinus", "PointlessArithmeticExpression"})
public class Spaceship extends AbstractPhasedStructure {
	public static final Spaceship INSTANCE = new Spaceship();
	private static final Spaceship2 part2 = new Spaceship2();
	private Spaceship() {}
	Block Block1 = ModBlocks.deco_tungsten;
	Block Block2 = ModBlocks.deco_red_copper;
	Block Block3 = ModBlocks.deco_steel;
	Block Block4 = ModBlocks.fusion_heater;
	Block Block5 = ModBlocks.block_meteor;
	Block Block7 = ModBlocks.cable_switch;
	Block Block8 = ModBlocks.fusion_hatch;
	Block Block9 = ModBlocks.reinforced_light;
	Block Block10 = ModBlocks.reinforced_glass;
	Block Block11 = ModBlocks.hadron_coil_alloy;
	Block Block12 = ModBlocks.pwr_fuelrod;

	@Override
	public void buildStructure(@NotNull LegacyBuilder builder, @NotNull Random rand) {
		generate_r0(builder, rand, 0, 0, 0);
	}

	@Override
	public boolean checkSpawningConditions(@NotNull World world, long pos) {
		int ox = Library.getBlockPosX(pos);
		int oy = Library.getBlockPosY(pos);
		int oz = Library.getBlockPosZ(pos);
		return locationIsValidSpawn(world, pos) &&
				locationIsValidSpawn(world, Library.blockPosToLong(ox + 12, oy, oz)) &&
				locationIsValidSpawn(world, Library.blockPosToLong(ox, oy, oz + 23)) &&
				locationIsValidSpawn(world, Library.blockPosToLong(ox + 12, oy, oz + 23));
	}

    @Override
    protected boolean isValidSpawnBlock(Block block) {
        return block == Blocks.GRASS || block == Blocks.DIRT || block == Blocks.STONE || block == Blocks.SAND || block == Blocks.SANDSTONE;
    }

    @Override
    public boolean isCacheable(){
        return false;
    }

	@Override
	public @NotNull LongArrayList getHeightPoints(long origin) {
		int ox = Library.getBlockPosX(origin);
		int oy = Library.getBlockPosY(origin);
		int oz = Library.getBlockPosZ(origin);
		LongArrayList points = new LongArrayList(4);
		points.add(origin);
		points.add(Library.blockPosToLong(ox + 12, oy, oz));
		points.add(Library.blockPosToLong(ox, oy, oz + 23));
		points.add(Library.blockPosToLong(ox + 12, oy, oz + 23));
		return points;
	}

	public boolean generate_r0(LegacyBuilder world, Random rand, int x, int y, int z)
	{
		MutableBlockPos pos = this.mutablePos;

		y += 1;
		
		world.setBlockState(pos.setPos(x + 2, y + -3, z + 10), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -3, z + 11), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 11), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -3, z + 12), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 12), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -3, z + 13), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 13), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -3, z + 14), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 14), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -3, z + 15), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 15), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -3, z + 16), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 16), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -3, z + 17), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -3, z + 17), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 17), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -3, z + 18), Block1.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -3, z + 18), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -3, z + 18), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 18), Block1.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -3, z + 19), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -3, z + 19), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -3, z + 19), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 19), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 19), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 19), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -3, z + 19), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 19), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -3, z + 20), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -3, z + 20), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -3, z + 20), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 20), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 20), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 20), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 20), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 20), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -3, z + 20), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 20), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -3, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -3, z + 21), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -3, z + 21), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 21), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 21), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 21), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 21), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 21), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -3, z + 21), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -3, z + 22), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -3, z + 22), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -3, z + 22), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 22), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 22), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 22), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 22), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 22), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -3, z + 22), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 22), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -3, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -3, z + 23), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -3, z + 23), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 23), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 23), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 23), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -3, z + 23), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -3, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -3, z + 24), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -3, z + 24), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 24), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -3, z + 24), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -3, z + 25), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -3, z + 25), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -3, z + 25), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 25), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -3, z + 25), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 25), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -3, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -3, z + 26), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -3, z + 26), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 26), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -3, z + 26), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -3, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -3, z + 27), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -3, z + 27), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 27), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -3, z + 27), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -3, z + 28), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -3, z + 28), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -3, z + 28), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 28), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -3, z + 28), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 28), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -3, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -3, z + 29), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -3, z + 29), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 29), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -3, z + 29), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -3, z + 30), ModBlocks.red_wire_coated.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -3, z + 30), ModBlocks.red_cable.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -3, z + 30), ModBlocks.red_wire_coated.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 30), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 30), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 30), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 30), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 30), ModBlocks.red_wire_coated.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -3, z + 30), ModBlocks.red_cable.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 30), ModBlocks.red_wire_coated.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -3, z + 31), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 31), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -3, z + 32), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 32), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 32), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 32), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 32), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 32), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -3, z + 33), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 33), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 33), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 33), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 33), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 33), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -3, z + 34), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 34), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 34), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 34), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 34), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 34), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -3, z + 35), Block4.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 35), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 35), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 35), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 35), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -3, z + 35), Block4.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 36), ModBlocks.red_wire_coated.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 36), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 36), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 36), ModBlocks.red_wire_coated.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 37), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 37), Block1.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 37), Block1.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 37), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -3, z + 38), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 38), Block1.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 38), Block1.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 38), Block1.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 38), Block1.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -3, z + 39), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 39), Block1.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 39), Block1.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 39), Block1.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 39), Block1.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -3, z + 39), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -3, z + 40), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 40), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 40), Block1.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 40), Block1.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -3, z + 40), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -3, z + 41), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 41), Block1.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -3, z + 41), Block1.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -3, z + 42), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -2, z + 6), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -2, z + 7), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 7), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -2, z + 8), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 8), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -2, z + 9), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -2, z + 9), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 9), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 9), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -2, z + 10), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -2, z + 10), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 10), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 10), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 10), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -2, z + 11), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -2, z + 11), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 11), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 11), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 11), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 11), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -2, z + 12), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -2, z + 12), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 12), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 12), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 12), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 12), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 12), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -2, z + 13), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -2, z + 13), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 13), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 13), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 13), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 13), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 13), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 13), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -2, z + 14), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -2, z + 14), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 14), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 14), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 14), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 14), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 14), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 14), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 14), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -2, z + 15), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -2, z + 15), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 15), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 15), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 15), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 15), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 15), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 15), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 15), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 15), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 15), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -2, z + 16), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -2, z + 16), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 16), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 16), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 16), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 16), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 16), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 16), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 16), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 16), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 16), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 16), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -2, z + 17), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -2, z + 17), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 17), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 17), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 17), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 17), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 17), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 17), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 17), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 17), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 17), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 17), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -2, z + 18), Block1.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -2, z + 18), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 18), Block1.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 18), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 18), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 18), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 18), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 18), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 18), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 18), Block1.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 18), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 18), Block1.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -2, z + 19), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -2, z + 19), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 19), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 19), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 19), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 19), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 19), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 19), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 19), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 19), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 19), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 19), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -2, z + 20), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -2, z + 20), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 20), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 20), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 20), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 20), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 20), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 20), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 20), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 20), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 20), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 20), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -2, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -2, z + 21), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 21), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 21), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 21), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 21), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 21), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 21), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 21), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -2, z + 22), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -2, z + 22), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 22), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 22), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 22), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 22), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 22), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 22), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 22), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 22), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 22), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 22), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -2, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -2, z + 23), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 23), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 23), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 23), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 23), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 23), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 23), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 23), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -2, z + 24), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 24), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 24), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 24), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -2, z + 25), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -2, z + 25), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 25), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 25), Blocks.CHEST.getDefaultState().withProperty(BlockChest.FACING, EnumFacing.EAST),
				(worldIn, random, blockPos, chest) ->
						WeightedRandomChestContentFrom1710.generateChestContents(random, ItemPool.getPool(ItemPoolsLegacy.POOL_SPACESHIP), chest, 12));
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 25), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 25), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 25), Blocks.CHEST.getDefaultState().withProperty(BlockChest.FACING, EnumFacing.WEST),
				(worldIn, random, blockPos, chest) ->
						WeightedRandomChestContentFrom1710.generateChestContents(rand, ItemPool.getPool(ItemPoolsLegacy.POOL_SPACESHIP), chest, 12));
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 25), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 25), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 25), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -2, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -2, z + 26), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 26), Blocks.CHEST.getDefaultState().withProperty(BlockChest.FACING, EnumFacing.EAST),
				(worldIn, random, blockPos, chest) ->
						WeightedRandomChestContentFrom1710.generateChestContents(rand, ItemPool.getPool(ItemPoolsLegacy.POOL_SPACESHIP), chest, 12));
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 26), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 26), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 26), Blocks.CHEST.getDefaultState().withProperty(BlockChest.FACING, EnumFacing.WEST),
				(worldIn, random, blockPos, chest) ->
						WeightedRandomChestContentFrom1710.generateChestContents(rand, ItemPool.getPool(ItemPoolsLegacy.POOL_SPACESHIP), chest, 12));
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 26), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -2, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -2, z + 27), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 27), Block11.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 27), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 27), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 27), Block11.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 27), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -2, z + 28), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -2, z + 28), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 28), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 28), Block5.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 28), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 28), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 28), Block5.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 28), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 28), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 28), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -2, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -2, z + 29), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 29), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 29), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 29), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 29), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 29), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -2, z + 30), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -2, z + 30), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 30), ModBlocks.red_cable.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 30), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 30), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 30), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 30), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 30), ModBlocks.red_cable.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 30), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 30), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -2, z + 31), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -2, z + 31), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 31), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 31), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 31), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 31), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 31), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 31), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 31), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 31), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -2, z + 32), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -2, z + 32), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 32), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 32), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 32), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 32), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 32), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 32), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 32), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 32), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 32), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 32), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -2, z + 33), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -2, z + 33), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 33), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 33), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 33), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 33), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 33), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 33), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 33), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 33), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 33), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 33), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -2, z + 34), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -2, z + 34), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 34), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 34), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 34), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 34), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 34), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 34), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 34), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 34), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 34), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 34), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -2, z + 35), Block4.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -2, z + 35), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 35), Block4.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 35), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 35), ModBlocks.machine_battery.getDefaultState().withProperty(MachineBattery.FACING, EnumFacing.EAST), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 35), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 35), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 35), ModBlocks.machine_battery.getDefaultState().withProperty(MachineBattery.FACING, EnumFacing.WEST), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 35), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 35), Block4.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 35), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -2, z + 35), Block4.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -2, z + 36), ModBlocks.red_wire_coated.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 36), ModBlocks.red_cable.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 36), ModBlocks.red_wire_coated.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 36), ModBlocks.red_cable.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 36), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 36), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 36), ModBlocks.red_cable.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 36), ModBlocks.red_wire_coated.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 36), ModBlocks.red_cable.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -2, z + 36), ModBlocks.red_wire_coated.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 37), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 37), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 37), Blocks.STONE_STAIRS.getDefaultState().withProperty(BlockStairs.HALF, BlockStairs.EnumHalf.BOTTOM).withProperty(BlockStairs.FACING, EnumFacing.NORTH), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 37), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 37), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 37), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 38), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 38), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 38), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 38), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 38), Blocks.CHEST.getDefaultState().withProperty(BlockChest.FACING, EnumFacing.NORTH),
				(worldIn, random, blockPos, chest) -> {
					WeightedRandomChestContentFrom1710.generateChestContents(random, ItemPool.getPool(ItemPoolsLegacy.POOL_EXPENSIVE), chest, 12);
					if(worldIn.rand.nextInt(10) == 0){
						IItemHandlerModifiable handle = (IItemHandlerModifiable)chest.getCapability(CapabilityItemHandler.ITEM_HANDLER_CAPABILITY, null);
						handle.setStackInSlot(random.nextInt(handle.getSlots()), new ItemStack(ModItems.gun_vortex));
					}
		});
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 38), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 39), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 39), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 39), Block7.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 39), Block8.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 39), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 39), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 40), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 40), Block1.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 40), Block4.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 40), Block4.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 40), Block1.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 40), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -2, z + 41), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 41), Block1.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 41), Block4.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 41), Block4.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 41), Block1.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -2, z + 30), Block12.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -2, z + 30), Block12.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -2, z + 41), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 42), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 42), Block1.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 42), Block1.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 42), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -2, z + 43), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 43), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 43), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -2, z + 43), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -2, z + 44), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -2, z + 44), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 2), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 3), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -1, z + 3), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 4), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -1, z + 4), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -1, z + 5), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 5), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -1, z + 5), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -1, z + 5), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -1, z + 5), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -1, z + 6), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 6), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -1, z + 6), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -1, z + 6), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -1, z + 6), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -1, z + 6), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -1, z + 7), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 7), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -1, z + 7), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -1, z + 7), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -1, z + 7), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -1, z + 7), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -1, z + 8), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 8), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -1, z + 8), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -1, z + 8), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -1, z + 8), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -1, z + 8), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + -1, z + 9), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 9), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -1, z + 9), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 9), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -1, z + 9), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -1, z + 9), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -1, z + 9), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 10), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -1, z + 10), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 10), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 10), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 10), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -1, z + 10), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -1, z + 10), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -1, z + 10), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + -1, z + 10), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 11), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -1, z + 11), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 11), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 11), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 11), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -1, z + 11), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -1, z + 11), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -1, z + 11), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -1, z + 11), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 12), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -1, z + 12), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 12), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 12), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 12), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -1, z + 12), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -1, z + 12), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -1, z + 12), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -1, z + 12), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -1, z + 12), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 13), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -1, z + 13), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 13), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 13), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 13), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -1, z + 13), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -1, z + 13), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -1, z + 13), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -1, z + 13), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -1, z + 13), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 14), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -1, z + 14), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 14), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 14), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 14), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -1, z + 14), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -1, z + 14), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -1, z + 14), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -1, z + 14), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -1, z + 14), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 15), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -1, z + 15), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 15), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 15), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 15), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -1, z + 15), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -1, z + 15), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -1, z + 15), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -1, z + 15), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -1, z + 15), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 16), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -1, z + 16), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 16), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 16), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 16), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -1, z + 16), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -1, z + 16), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -1, z + 16), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -1, z + 16), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -1, z + 16), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 17), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -1, z + 17), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 17), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 17), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 17), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -1, z + 17), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -1, z + 17), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -1, z + 17), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -1, z + 17), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -1, z + 17), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 18), Block1.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -1, z + 18), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 18), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 18), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 18), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -1, z + 18), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -1, z + 18), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -1, z + 18), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -1, z + 18), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -1, z + 18), Block1.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 19), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -1, z + 19), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 19), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 19), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 19), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -1, z + 19), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -1, z + 19), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -1, z + 19), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -1, z + 19), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -1, z + 19), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 20), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -1, z + 20), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 20), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 20), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 20), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -1, z + 20), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -1, z + 20), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -1, z + 20), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -1, z + 20), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -1, z + 20), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -1, z + 21), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 21), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 21), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 21), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -1, z + 21), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -1, z + 21), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -1, z + 21), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -1, z + 21), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -1, z + 21), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 22), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -1, z + 22), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 22), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 22), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 22), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -1, z + 22), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -1, z + 22), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -1, z + 22), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -1, z + 22), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -1, z + 22), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -1, z + 23), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 23), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 23), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 23), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -1, z + 23), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -1, z + 23), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -1, z + 23), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -1, z + 23), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -1, z + 23), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -1, z + 24), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 24), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -1, z + 24), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -1, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -1, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -1, z + 24), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -1, z + 24), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 25), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -1, z + 25), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 25), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 25), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -1, z + 25), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -1, z + 25), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -1, z + 25), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -1, z + 25), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -1, z + 25), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -1, z + 26), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 26), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 26), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -1, z + 26), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -1, z + 26), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -1, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -1, z + 26), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -1, z + 26), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -1, z + 27), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 27), Block9.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 27), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 27), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -1, z + 27), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -1, z + 27), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -1, z + 27), Block9.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -1, z + 27), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -1, z + 27), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 28), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -1, z + 28), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 28), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 28), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -1, z + 28), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -1, z + 28), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -1, z + 28), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -1, z + 28), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -1, z + 28), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -1, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 29), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 29), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -1, z + 29), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -1, z + 29), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -1, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -1, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -1, z + 29), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 30), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -1, z + 30), ModBlocks.machine_generator.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 30), ModBlocks.red_cable.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 30), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 30), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -1, z + 30), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -1, z + 30), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -1, z + 30), ModBlocks.red_cable.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -1, z + 30), ModBlocks.machine_generator.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -1, z + 30), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 31), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -1, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 31), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 31), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -1, z + 31), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -1, z + 31), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -1, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -1, z + 31), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -1, z + 31), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 32), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + -1, z + 32), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 32), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 32), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 32), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -1, z + 32), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -1, z + 32), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -1, z + 32), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + -1, z + 32), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -1, z + 32), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 33), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 33), Block9.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 33), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 33), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -1, z + 33), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -1, z + 33), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -1, z + 33), Block9.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -1, z + 33), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 34), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 34), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 34), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 34), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -1, z + 34), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -1, z + 34), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -1, z + 34), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -1, z + 34), Block2.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + -1, z + 35), Block4.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 35), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 35), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 35), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -1, z + 35), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -1, z + 35), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -1, z + 35), Block3.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + -1, z + 35), Block4.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 36), Block10.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 36), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 36), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -1, z + 36), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -1, z + 36), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -1, z + 36), Block10.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 37), Block10.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 37), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 37), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -1, z + 37), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -1, z + 37), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -1, z + 37), Block10.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 38), Block10.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 38), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 38), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -1, z + 38), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -1, z + 38), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -1, z + 38), Block10.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 39), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 39), Block10.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 39), Block10.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -1, z + 39), Block10.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -1, z + 39), Block10.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -1, z + 39), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 40), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 40), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 40), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -1, z + 40), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -1, z + 40), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -1, z + 40), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 41), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 41), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 41), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -1, z + 41), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -1, z + 41), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + -1, z + 42), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 42), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 42), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -1, z + 42), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -1, z + 42), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -1, z + 42), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + -1, z + 43), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 43), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -1, z + 43), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -1, z + 43), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + -1, z + 43), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 44), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -1, z + 44), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + -1, z + 44), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + -1, z + 45), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + -1, z + 45), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + 0, z + 0), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + 0, z + 0), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + 0, z + 1), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + 0, z + 1), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + 0, z + 2), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + 0, z + 2), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + 0, z + 2), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + 0, z + 2), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + 0, z + 3), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + 0, z + 3), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + 0, z + 3), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + 0, z + 3), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + 0, z + 3), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + 0, z + 3), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + 0, z + 4), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + 0, z + 4), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + 0, z + 4), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + 0, z + 4), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + 0, z + 4), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 12, y + 0, z + 4), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 1, y + 0, z + 5), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + 0, z + 5), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + 0, z + 5), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + 0, z + 5), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + 0, z + 5), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + 0, z + 6), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + 0, z + 6), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + 0, z + 6), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + 0, z + 6), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + 0, z + 7), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + 0, z + 7), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + 0, z + 7), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + 0, z + 7), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + 0, z + 7), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + 0, z + 8), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + 0, z + 8), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + 0, z + 8), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + 0, z + 8), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + 0, z + 8), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + 0, z + 8), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + 0, z + 8), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + 0, z + 9), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + 0, z + 9), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + 0, z + 9), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + 0, z + 9), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + 0, z + 9), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + 0, z + 9), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + 0, z + 9), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + 0, z + 9), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + 0, z + 9), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + 0, z + 10), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + 0, z + 10), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + 0, z + 10), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + 0, z + 10), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + 0, z + 10), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + 0, z + 10), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + 0, z + 10), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + 0, z + 10), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + 0, z + 10), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 11, y + 0, z + 10), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + 0, z + 11), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + 0, z + 11), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + 0, z + 11), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + 0, z + 11), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + 0, z + 11), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + 0, z + 11), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + 0, z + 11), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + 0, z + 11), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + 0, z + 11), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + 0, z + 12), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + 0, z + 12), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + 0, z + 12), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + 0, z + 12), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + 0, z + 12), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + 0, z + 12), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + 0, z + 12), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + 0, z + 12), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + 0, z + 12), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + 0, z + 13), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + 0, z + 13), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + 0, z + 13), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + 0, z + 13), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + 0, z + 13), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + 0, z + 13), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + 0, z + 13), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + 0, z + 13), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + 0, z + 13), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + 0, z + 14), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + 0, z + 14), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + 0, z + 14), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + 0, z + 14), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + 0, z + 14), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + 0, z + 14), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + 0, z + 14), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + 0, z + 14), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + 0, z + 14), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + 0, z + 15), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + 0, z + 15), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + 0, z + 15), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + 0, z + 15), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + 0, z + 15), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + 0, z + 15), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + 0, z + 15), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + 0, z + 15), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + 0, z + 15), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + 0, z + 16), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + 0, z + 16), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + 0, z + 16), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + 0, z + 16), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + 0, z + 16), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + 0, z + 16), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + 0, z + 16), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 9, y + 0, z + 16), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 10, y + 0, z + 16), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 2, y + 0, z + 17), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 3, y + 0, z + 17), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 4, y + 0, z + 17), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 5, y + 0, z + 17), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 6, y + 0, z + 17), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 7, y + 0, z + 17), Blocks.AIR.getDefaultState(), 3);
		world.setBlockState(pos.setPos(x + 8, y + 0, z + 17), Blocks.AIR.getDefaultState(), 3);

		part2.generate_r00(world, rand, x, y, z);
		return true;

	}
}
